export default {
  ADD_POST: 'ADD_POST',
  ADD_COMMENT: 'ADD_COMMENT',
  INCREMENT_LIKES: 'INCREMENT_LIKES',
  REMOVE_COMMENT: 'REMOVE_COMMENT',
  LOAD_COMMENTS: 'LOAD_COMMENTS',
  LOAD_POSTS: 'LOAD_POSTS'
};
